services:
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    networks:
      - greenit_network
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    networks:
      - greenit_network

networks:
  greenit_network:
    external: true